import type { Locale } from "./store";

export const copy = {
  en: {
    navComponents: "Components",
    navApi: "API",
    navInstall: "Install",
    navGithub: "GitHub",
    language: "中文",
    eyebrow: "Native UI for Go, with a breeze.",
    title: "Build native interfaces with a familiar utility vocabulary.",
    intro:
      "Breeze UI brings Tailwind-inspired tokens, utilities, and accessible components to MyGo's GPU-rendered native UI. No DOM. No CSS runtime. Just typed Go.",
    start: "Get started",
    explore: "Explore components",
    components: "components",
    utilities: "utilities",
    dependencies: "runtime dependencies",
    calmTitle: "A calm layer over native UI",
    calmText:
      "Keep the speed and control of native rendering while giving your team a consistent design language.",
    utilityTitle: "Utility-first, Go-native",
    utilityText:
      "Compose typed styles with familiar spacing, layout, color, and typography helpers.",
    componentTitle: "Components with behavior included",
    componentText:
      "Buttons, fields, dialogs, tabs, and more delegate focus, keyboard, and accessibility to MyGo's native primitives.",
    toolingTitle: "Tooling that stays out of the way",
    toolingText:
      "Use the CLI to discover the catalog, or connect the MCP server to your coding workflow.",
    aiKicker: "AI-native tooling",
    aiTitle: "A familiar home for your AI stack",
    aiText:
      "Bring native MyGo surfaces to the models and coding agents your team already uses. Breeze UI stays focused on the interface layer.",
    aiSource: "Powered by ai-logo",
    aiOpenAi: "Models and agents",
    aiClaude: "Thoughtful workflows",
    aiGemini: "Multimodal products",
    aiCursor: "Fast iteration",
    aiCodex: "Code-first tools",
    aiDeepSeek: "Open model workflows",
    aiDisclaimer: "Brand marks are shown for identification only and do not imply endorsement.",
    catalogKicker: "The catalog",
    catalogTitle: "A small, deliberate catalog",
    catalogText:
      "Start with the primitives you use every day. Each item is typed, composable, and documented.",
    all: "All",
    component: "Components",
    utility: "Utilities",
    token: "Tokens",
    installKicker: "Start here",
    installTitle: "One package. Native rendering.",
    installText:
      "Add Breeze UI to an existing MyGo app or run the gallery to see every primitive in motion.",
    docs: "Read the docs",
    copy: "Copy",
    copied: "Copied",
    apiKicker: "API reference",
    apiTitle: "The catalog is yours to query",
    apiText:
      "Use the typed Go package locally, or integrate the catalog into internal tools through a stable, versioned API shape.",
    apiLink: "Explore API docs",
    starTitle: "Build in the open",
    starText: "Breeze UI is MIT licensed and evolving with the MyGo ecosystem.",
    source: "Source on GitHub",
    footer: "Breeze UI for MyGo",
    apiSearch: "Try the catalog query",
    apiSearchPlaceholder: "Search components, utilities, tokens…",
    apiRun: "Run query",
    apiResult: "Validated request",
    method: "Method",
    response: "Example response",
  },
  zh: {
    navComponents: "组件",
    navApi: "API",
    navInstall: "安装",
    navGithub: "GitHub",
    language: "English",
    eyebrow: "为 Go 打造的原生 UI，轻盈如风。",
    title: "用熟悉的工具样式，构建真正的原生界面。",
    intro:
      "Breeze UI 将 Tailwind 风格的设计令牌、工具样式和可访问组件带到 MyGo 的 GPU 原生 UI 中。不需要 DOM，不需要运行时 CSS，只需要类型安全的 Go。",
    start: "开始使用",
    explore: "浏览组件",
    components: "个组件",
    utilities: "个工具样式",
    dependencies: "运行时依赖",
    calmTitle: "原生 UI 之上的平静一层",
    calmText: "保留原生渲染的速度与控制力，同时让团队拥有统一的设计语言。",
    utilityTitle: "Go 原生的 Utility-first",
    utilityText: "用熟悉的间距、布局、颜色和排版工具组合出类型安全的样式。",
    componentTitle: "自带行为的组件",
    componentText: "按钮、输入框、对话框、标签页等组件将焦点、键盘和可访问性交给 MyGo 原生基元。",
    toolingTitle: "不会碍事的工具链",
    toolingText: "用 CLI 浏览组件目录，或把 MCP 服务接入你的编码工作流。",
    aiKicker: "AI 原生工具链",
    aiTitle: "为你的 AI 工具栈留出一层原生界面",
    aiText:
      "把 MyGo 的原生窗口带到团队已经在使用的模型和编程 Agent 旁边。Breeze UI 专注于界面这一层。",
    aiSource: "由 ai-logo 提供图标",
    aiOpenAi: "模型与 Agent",
    aiClaude: "更从容的工作流",
    aiGemini: "多模态产品",
    aiCursor: "快速迭代",
    aiCodex: "代码优先工具",
    aiDeepSeek: "开放模型工作流",
    aiDisclaimer: "品牌标识仅用于识别，不代表相关方背书。",
    catalogKicker: "组件目录",
    catalogTitle: "小而明确的组件目录",
    catalogText: "从每天都会用到的基础组件开始。每个条目都类型安全、可组合并有文档。",
    all: "全部",
    component: "组件",
    utility: "工具样式",
    token: "令牌",
    installKicker: "从这里开始",
    installTitle: "一个包，原生渲染。",
    installText: "把 Breeze UI 加进现有 MyGo 应用，或运行组件展示查看所有基础能力。",
    docs: "阅读文档",
    copy: "复制",
    copied: "已复制",
    apiKicker: "API 文档",
    apiTitle: "组件目录可以直接查询",
    apiText: "在 Go 包中使用类型安全的 API，也可以把版本化目录接入内部工具。",
    apiLink: "查看 API 文档",
    starTitle: "在开源中一起构建",
    starText: "Breeze UI 使用 MIT 协议，和 MyGo 生态一起持续演进。",
    source: "在 GitHub 查看源码",
    footer: "Breeze UI for MyGo",
    apiSearch: "试试目录查询",
    apiSearchPlaceholder: "搜索组件、工具样式、令牌…",
    apiRun: "执行查询",
    apiResult: "已验证请求",
    method: "方法",
    response: "示例响应",
  },
} as const;

export function useCopy(locale: Locale) {
  return copy[locale];
}
