import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js"
import { fileURLToPath } from "node:url"
import { z } from "zod"

import { findCatalog, loadCatalog, searchCatalog } from "./catalog.js"

const serverInfo = {
  name: "breeze-ui",
  version: "0.1.0",
}

function textResult(value: unknown) {
  return { content: [{ type: "text" as const, text: JSON.stringify(value, null, 2) }] }
}

export function createServer() {
  const server = new McpServer(serverInfo)
  const catalog = loadCatalog()

  server.registerTool(
    "search_components",
    {
      title: "Search Breeze UI components",
      description: "Find components in the Breeze UI catalog for MyGo.",
      inputSchema: { query: z.string().optional() },
      annotations: { readOnlyHint: true },
    },
    ({ query }) => textResult(searchCatalog("component", query, catalog))
  )

  server.registerTool(
    "get_component",
    {
      title: "Get a Breeze UI component",
      description: "Return the catalog entry for one component by name.",
      inputSchema: { name: z.string() },
      annotations: { readOnlyHint: true },
    },
    ({ name }) => {
      const item = findCatalog("component", name, catalog)
      return item ? textResult(item) : textResult({ error: `Unknown component: ${name}` })
    }
  )

  server.registerTool(
    "search_utilities",
    {
      title: "Search Breeze UI utilities",
      description: "Find Tailwind-style layout and visual utility helpers.",
      inputSchema: { query: z.string().optional() },
      annotations: { readOnlyHint: true },
    },
    ({ query }) => textResult(searchCatalog("utility", query, catalog))
  )

  server.registerTool(
    "get_token",
    {
      title: "Get a Breeze UI token",
      description: "Return a spacing, radius, or typography token by name.",
      inputSchema: { name: z.string() },
      annotations: { readOnlyHint: true },
    },
    ({ name }) => {
      const item = findCatalog("token", name, catalog)
      return item ? textResult(item) : textResult({ error: `Unknown token: ${name}` })
    }
  )

  server.registerTool(
    "generate_snippet",
    {
      title: "Generate a Breeze UI snippet",
      description: "Generate a Go snippet for a catalog component.",
      inputSchema: { component: z.string() },
      annotations: { readOnlyHint: true },
    },
    ({ component }) => {
      const item = findCatalog("component", component, catalog)
      if (!item) return textResult({ error: `Unknown component: ${component}` })
      return textResult({
        component: item.name,
        code: `// Generated by breeze-ui MCP.\n// Package breeze: github.com/yldm-tech/mygo-breeze-ui/ui/breeze\n\n${item.example}\n`,
      })
    }
  )

  server.registerResource(
    "catalog",
    "breeze-ui://catalog",
    { title: "Breeze UI catalog", description: "Components, utilities, and tokens for Breeze UI for MyGo.", mimeType: "application/json" },
    (uri) => ({ contents: [{ uri: uri.href, mimeType: "application/json", text: JSON.stringify(catalog, null, 2) }] })
  )

  return server
}

export async function main() {
  const server = createServer()
  await server.connect(new StdioServerTransport())
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) await main()
