// Command breeze-ui scaffolds and discovers Breeze UI for MyGo.
package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	breeze "github.com/yldm-tech/mygo-breeze-ui/ui/breeze"
)

const usage = `breeze-ui is the CLI for github.com/yldm-tech/mygo-breeze-ui/ui/breeze.

Usage:

  breeze-ui list [-kind utility|component|token]
  breeze-ui add <component> [-o path]
  breeze-ui tokens [-o path]
  breeze-ui init [dir] [--force]
  breeze-ui example
`

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, "breeze-ui:", err)
		os.Exit(1)
	}
}

func run(args []string, out io.Writer) error {
	if len(args) == 0 || args[0] == "help" || args[0] == "-h" || args[0] == "--help" {
		_, _ = io.WriteString(out, usage)
		return nil
	}
	switch args[0] {
	case "list":
		return list(args[1:], out)
	case "add":
		return add(args[1:], out)
	case "tokens":
		return tokens(args[1:], out)
	case "init":
		return initProject(args[1:], out)
	case "example":
		_, _ = io.WriteString(out, example)
		return nil
	default:
		return fmt.Errorf("unknown command %q; run breeze-ui --help", args[0])
	}
}

func list(args []string, out io.Writer) error {
	fs := flag.NewFlagSet("list", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	kind := fs.String("kind", "", "filter by utility, component, or token")
	if err := fs.Parse(normalizeFlagArgs(args, map[string]bool{"-kind": true, "--kind": true})); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return errors.New("list takes no positional arguments")
	}
	for _, item := range breeze.Catalog() {
		if *kind != "" && item.Kind != *kind {
			continue
		}
		if item.Kind == "token" && item.Value != "" {
			fmt.Fprintf(out, "%s\t%s\t%s\n", item.Kind, item.Name, item.Value)
		} else {
			fmt.Fprintf(out, "%s\t%s\n", item.Kind, item.Name)
		}
	}
	return nil
}

func add(args []string, out io.Writer) error {
	fs := flag.NewFlagSet("add", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	path := fs.String("o", "", "write the snippet to a file instead of stdout")
	if err := fs.Parse(normalizeFlagArgs(args, map[string]bool{"-o": true, "--o": true, "--output": true})); err != nil {
		return err
	}
	if fs.NArg() != 1 {
		return errors.New("add requires one component name")
	}
	item, ok := breeze.FindKind("component", fs.Arg(0))
	if !ok {
		return fmt.Errorf("unknown component %q; run breeze-ui list -kind component", fs.Arg(0))
	}
	snippet := fmt.Sprintf("// Generated by breeze-ui add %s.\n// Package breeze: github.com/yldm-tech/mygo-breeze-ui/ui/breeze\n\n%s\n", item.Name, item.Example)
	return writeOutput(*path, snippet, out)
}

func tokens(args []string, out io.Writer) error {
	fs := flag.NewFlagSet("tokens", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	path := fs.String("o", "", "write the generated Go file to a path")
	if err := fs.Parse(normalizeFlagArgs(args, map[string]bool{"-o": true, "--o": true, "--output": true})); err != nil {
		return err
	}
	if fs.NArg() != 0 {
		return errors.New("tokens takes no positional arguments")
	}
	items := []breeze.CatalogItem{}
	for _, item := range breeze.Catalog() {
		if item.Kind == "token" {
			items = append(items, item)
		}
	}
	sort.Slice(items, func(i, j int) bool { return items[i].Name < items[j].Name })
	var b strings.Builder
	b.WriteString("// Code generated by breeze-ui tokens; DO NOT EDIT.\npackage theme\n\n")
	for _, item := range items {
		name := exportedTokenName(item.Name)
		value, err := strconv.ParseFloat(item.Value, 32)
		if err != nil {
			return fmt.Errorf("token %s has invalid numeric value %q", item.Name, item.Value)
		}
		fmt.Fprintf(&b, "const %s float32 = %g\n", name, value)
	}
	return writeOutput(*path, b.String(), out)
}

func initProject(args []string, out io.Writer) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	force := fs.Bool("force", false, "replace generated files")
	if err := fs.Parse(normalizeFlagArgs(args, map[string]bool{"--force": false})); err != nil {
		return err
	}
	if fs.NArg() > 1 {
		return errors.New("init takes at most one directory")
	}
	dir := "."
	if fs.NArg() == 1 {
		dir = fs.Arg(0)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	config := "{\n  \"library\": \"github.com/yldm-tech/mygo-breeze-ui/ui/breeze\",\n  \"catalogVersion\": 1\n}\n"
	path := filepath.Join(dir, "breeze-ui.json")
	if !*force {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("%s already exists; pass --force to replace it", path)
		} else if !os.IsNotExist(err) {
			return err
		}
	}
	if err := os.WriteFile(path, []byte(config), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(out, "created %s\n", path)
	return nil
}

// normalizeFlagArgs lets users put options before or after positional
// arguments. The standard flag package stops parsing at the first positional
// argument, while commands such as `breeze-ui add Button -o button.go` are a
// natural spelling for a CLI. Values belonging to known options stay next to
// their option; positionals are moved to the end in their original order.
func normalizeFlagArgs(args []string, valueFlags map[string]bool) []string {
	flags := make([]string, 0, len(args))
	positionals := make([]string, 0, len(args))
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if !strings.HasPrefix(arg, "-") || arg == "-" {
			positionals = append(positionals, arg)
			continue
		}
		flags = append(flags, arg)
		name := arg
		if equals := strings.IndexByte(arg, '='); equals >= 0 {
			name = arg[:equals]
		}
		if valueFlags[name] && !strings.ContainsRune(arg, '=') && i+1 < len(args) {
			flags = append(flags, args[i+1])
			i++
		}
	}
	return append(flags, positionals...)
}

func writeOutput(path, content string, out io.Writer) error {
	if path == "" {
		_, err := io.WriteString(out, content)
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil && !errors.Is(err, os.ErrExist) {
		return err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(out, "wrote %s\n", path)
	return nil
}

func exportedTokenName(name string) string {
	var b strings.Builder
	upper := true
	for _, r := range name {
		if r == '-' || r == '_' {
			upper = true
			continue
		}
		if upper {
			r = []rune(strings.ToUpper(string(r)))[0]
			upper = false
		}
		b.WriteRune(r)
	}
	return b.String()
}

const example = `package main

import (
    "github.com/egoist/mygo/ui"
    breeze "github.com/yldm-tech/mygo-breeze-ui/ui/breeze"
)

func view(c *ui.Context) {
    breeze.Card(c, func() {
        breeze.Text(c, "Welcome", breeze.TextSize(breeze.TextLG), breeze.FontWeight(600))
        if breeze.Button(c, "Continue", breeze.ButtonPrimary).Clicked() {
            // handle the action
        }
    })
}
`
